// File generated by hand to match `flutterfire configure` output.
// This project only targets Flutter web (see the `web/` directory and
// absence of android/ios/macos/windows folders), so only the web
// FirebaseOptions are defined. Run `flutterfire configure` locally if
// another platform target is added later to regenerate this file properly.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions have not been configured for '
      '${defaultTargetPlatform.name} — this project only targets web.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgUU5PSFZvzcZl0T13YRDApOiJjXO4zyE',
    authDomain: 'pierrejunior-portfolio.firebaseapp.com',
    projectId: 'pierrejunior-portfolio',
    storageBucket: 'pierrejunior-portfolio.firebasestorage.app',
    messagingSenderId: '636750549776',
    appId: '1:636750549776:web:69b8816394f34071698b95',
  );
}
